# Generated by Django 3.0.2 on 2020-02-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0002_customer_qq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
