# Generated by Django 3.0.2 on 2020-02-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0003_auto_20200201_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qq',
        ),
    ]
